/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Caller classUnderTest = new Caller();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
