#!/bin/bash

echo "--- Interleaved Query Testing ---"

# Make sure to update the jar path before running
JAR_PATH="/Users/simranmalik/Desktop/645-Lab-32966720340112693401883534060222/app/build/libs/app.jar"
echo "Running Query Test from $JAR_PATH"

#  Running the Query Test, displaying the output
java -cp "$JAR_PATH" buffer.QueryTest 2>&1 | tee query_results.log

# Check whether the query_results.log file is empty
if [ ! -s query_results.log ]; then
    echo "FAIL: Output not generated by QueryTest."
else
    echo "PASS: Query Test Completed. Output is saved to QueryResults.log."
fi

# Ensuring if any errors are present in the log
if grep -q "FAIL" query_results.log; then
    echo "FAIL: Query Test Failed! Check query_results.log."
    exit 1
else
    echo "PASS: Query Tests have passed."
fi

echo "All end to end tests have passed sucessfully!"
exit 0
