#!/bin/bash

echo "===== Running Interleaved Query Test ====="

# Ensure the JAR path is correct and the directory where you are executing the script has the correct JAR
JAR_PATH="/Users/simranmalik/Desktop/645-Lab-32966720340112693401883534060222/app/build/libs/app.jar"
echo "Running Query Test from $JAR_PATH"

#  Run the Query Test and display output in real-time
java -cp "$JAR_PATH" buffer.QueryTest 2>&1 | tee query_results.log

# Check if the query_results.log file is empty
if [ ! -s query_results.log ]; then
    echo "❌ No output generated by QueryTest."
else
    echo "✅ Query Test Completed. Output is saved to query_results.log."
fi

# Check if any errors are present in the log
if grep -q "❌" query_results.log; then
    echo "❌ Query Test Failed! Check query_results.log."
    exit 1
else
    echo "✅ Query Test Passed."
fi

echo "All end to end tests have passed sucessfully!!!!!"
exit 0
